### ISSUE TITLE
Invalid login makes Hallitse button appears

### ISSUE THREAD

**Issue by Abdullaharifbhatti** [oona988/snowledge#35]
Summary:

**Steps to reproduce:** 
1- Log in with invalid crendentials
2- Hallitse button appears without admin logging in.

**Expected result:**
-If logging in should be with wrong credentials then it shouldn't show Hallitse button.

**Actual result:**

-While logging in with the wrong credentials anyone can see the Hallitse button

**Platform (Chrome/Mobile/All...):**
-Chrome/Mobile chrome/Edge

**Possible causes of the bug:**
-Hallitse button only checks if a login was done but doesnt' check if it was successful.

**Any other additional information:**

**Comment by collandk** [comment]
This is fixed by Emil now. A login attempt with wrong credentials shows an error message to the user and Hallitse tab does not become visible.
