### ISSUE TITLE
Filter snow tab on the landing page

### ISSUE THREAD

**Issue by Abdullaharifbhatti** [oona988/snowledge#36]
**Summary:
Steps to reproduce:**
1- Login 
2- Update a segment from map
3- Open filters and see the snow types

**Expected result:**
Snow types should be listed once in the filters tab.

**Actual result:**
Snow types shows the replication of snow type names in the filter tab.

**Platform (Chrome/Mobile/All...):**
Chrome/FireFox/Edge/Safari mobile

**Screenshot?**
**WEB screen**
![Snow tab bug](https://user-images.githubusercontent.com/60933836/145587122-74a82d7a-134f-4fdf-9ee9-25307e3a5d52.PNG)

**Possible causes of the bug:**
Updating the segment replicates the snow name in the filter snow tab.
**Any other additional information:**

**Comment by collandk** [comment]
This is now fixed thanks to Emil! Verified the fix on mobile and web by editing segment informations and viewing the filters.
