### ISSUE TITLE
Mobile view navigation bar

### ISSUE THREAD

**Issue by Abdullaharifbhatti** [oona988/snowledge#37]
**Summary:
Steps to reproduce:**
1- Open the mobile version of the product

**Expected result:**
Navigation bar should be in the bottom of the mobile screen.

**Actual result:**
Navigation bar is not in the bottom.

**Platform (Chrome/Mobile/All...):**
Chrome mobile/Safari mobile.
**Screenshot?**
![IMG_0327](https://user-images.githubusercontent.com/60933836/145589477-9b17a466-5b2d-4ae9-a874-6546d156efb5.PNG)

**Possible causes of the bug:**
Navigation bar isn't showing at the right place
**Any other additional information:**

**Comment by collandk** [comment]
This is partly fixed: The layout bar does not move anymore. However, the welcome view "Näytä lumitilanne" button is too low, it is below the screen on mobile.

**Comment by collandk** [comment]
Welcome view button is now visible and stays in place
