### ISSUE TITLE
Snow updates are not updated correctly. 

### ISSUE THREAD

**Issue by Abdullaharifbhatti** [oona988/snowledge#39]
**Summary:
Steps to reproduce:**
1- Login
2- Click on any segment to update.
3- Update the snow record
4- Updated
5- Close the snow record pop up window and click again on the segment
-- Added here for more info -- 
6- Refresh the page 
7- Open the segment and see a wrong update

**Expected result:**
Snow record should be updated after a refresh

**Actual result:**
Snow records doesn't show the latest update when you open the segment again after closing and refreshing it.

**Platform (Chrome/Mobile/All...):**
Chrome web, Ipad pro, safari mobile, Chrome mobile, Firefox

**Possible causes of the bug:**
No idea for updating the snow record

Any other additional information:

**Comment by collandk** [comment]
1) Segment information not updating properly without a refresh is known behaviour and will be documented.

2) We were not able to reproduce the issue. Updates seemed to be working properly after refreshing the page. This issue will be reopened if the issue is seen again.
