### ISSUE TITLE
Second click on segment map opens forest segment info.

### ISSUE THREAD

**Issue by Abdullaharifbhatti** [oona988/snowledge#40]
**Summary:
Steps to reproduce:**
1- Login
2- Click on the segment map
3- Second click on the same segment map.
4- See the first click snow info and then on second click see the forest info?

**Expected result:**
Only show segment snow info.

**Actual result:**
showing snow info as well as forest information when you click 2 times on the same segment on map.

**Platform (Chrome/Mobile/All...):**
Chrome web, Safari mobile, Mircosoft edge, Ipad pro, FireFox.

**Possible causes of the bug:**
maybe 2 clicks on segment are not allowed (MAYBE). so on first click it shows the snow info but on second it just shows the Metsa info.

Any other additional information:

**Comment by collandk** [comment]
This error does not occur on the Tavu server now. However, we are not exactly sure why it occurs on the test server.
